name = "Shampoo"
uuid = "5be1adcc-c8d0-4ece-932e-72d2f9abdad2"
authors = ["Ziyi Yin <ziyi.yin@gatech.edu> and SLIM contributors"]
version = "0.1.0"

[deps]
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1"
JOLI = "0.7, 0.8"
Requires = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
